	demoinput ,	8
	demoinput R,	$100
	demoinput R,	$48
	demoinput ,	$C3
	demoinput L,	$3F
	demoinput ,	$13
	demoinput R,	$1B
	demoinput UR,	1
	demoinput R,	$F
	demoinput ,	2
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
