	demoinput ,	7
	demoinput R,	$11
	demoinput ,	$75
	demoinput R,	$30
	demoinput RC,	$1C
	demoinput R,	$55
	demoinput RD,	7
	demoinput D,	$21
	demoinput ,	$61
	demoinput C,	$1E
	demoinput RC,	$15
	demoinput R,	$12
	demoinput ,	$A
	demoinput R,	$20
	demoinput ,	4
	demoinput R,	7
	demoinput RD,	8
	demoinput D,	$27
	demoinput ,	$31
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
