	demoinput ,	5
	demoinput R,	$84
	demoinput ,	$93
	demoinput D,	$A
	demoinput ,	6
	demoinput D,	9
	demoinput ,	5
	demoinput D,	3
	demoinput ,	$10
	demoinput C,	7
	demoinput ,	$5F
	demoinput C,	7
	demoinput ,	$26
	demoinput D,	$B
	demoinput ,	7
	demoinput D,	9
	demoinput ,	8
	demoinput D,	6
	demoinput ,	$11
	demoinput C,	7
	demoinput ,	$70
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
