	demoinput R,	$65
	demoinput RC,	$A
	demoinput R,	$50
	demoinput RC,	$29
	demoinput R,	$14
	demoinput RC,	$A
	demoinput R,	$84
	demoinput RC,	$11
	demoinput R,	$44
	demoinput RC,	$17
	demoinput R,	$14
	demoinput RC,	$16
	demoinput R,	$1A
	demoinput RC,	7
	demoinput R,	$33
	demoinput RC,	$1C
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1