	demoinput ,	$26
	demoinput L,	$53
	demoinput ,	$26
	demoinput L,	$24
	demoinput ,	$E8
	demoinput L,	$69
	demoinput ,	$E
	demoinput R,	$6F
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1