	demoinput ,	9
	demoinput L,	$20
	demoinput ,	$B
	demoinput R,	$16
	demoinput RC,	$20
	demoinput URC,	3
	demoinput RC,	5
	demoinput C,	2
	demoinput ,	5
	demoinput L,	$23
	demoinput ,	$15
	demoinput L,	$1A
	demoinput ,	9
	demoinput L,	1
	demoinput LC,	8
	demoinput L,	4
	demoinput ,	$1E
	demoinput L,	$54
	demoinput ,	8
	demoinput R,	8
	demoinput ,	$69
	demoinput L,	8
	demoinput ,	$7D
	demoinput L,	9
	demoinput LC,	$F
	demoinput L,	$B
	demoinput ,	$1D
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
