	demoinput ,	9
	demoinput R,	$EE
	demoinput ,	$D
	demoinput D,	$22
	demoinput ,	$A5
	demoinput L,	$27
	demoinput LC,	7
	demoinput L,	$43
	demoinput LC,	2
	demoinput L,	$53
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
