	demoinput ,	$18
	demoinput R,	$30
	demoinput ,	$1B
	demoinput R,	$1D
	demoinput RD,	3
	demoinput D,	$A
	demoinput ,	8
	demoinput L,	$1C
	demoinput ,	$2A
	demoinput D,	$4C
	demoinput ,	$63
	demoinput D,	$4B
	demoinput ,	$4B
	demoinput C,	9
	demoinput RC,	8
	demoinput URC,	$23
	demoinput RC,	3
	demoinput C,	2
	demoinput ,	$38
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
