	demoinput ,	$A
	demoinput R,	$79
	demoinput ,	7
	demoinput R,	7
	demoinput ,	4
	demoinput C,	6
	demoinput RC,	$12
	demoinput R,	$E
	demoinput ,	$2C
	demoinput R,	3
	demoinput URC,	8
	demoinput UR,	3
	demoinput ,	8
	demoinput UL,	$10
	demoinput ,	9
	demoinput R,	$E
	demoinput RC,	8
	demoinput R,	$C
	demoinput ,	$29
	demoinput R,	1
	demoinput UR,	3
	demoinput URC,	3
	demoinput RC,	5
	demoinput R,	$13
	demoinput ,	$A
	demoinput R,	1
	demoinput URC,	3
	demoinput RC,	5
	demoinput R,	$A
	demoinput ,	$10
	demoinput R,	$D
	demoinput ,	$F
	demoinput UR,	1
	demoinput URC,	9
	demoinput UR,	3
	demoinput R,	$19
	demoinput ,	$A
	demoinput RC,	1
	demoinput URC,	$B
	demoinput UR,	$13
	demoinput R,	1
	demoinput ,	$19
	demoinput URC,	$11
	demoinput UR,	$11
	demoinput R,	4
	demoinput ,	$30
	demoinput UL,	7
	demoinput ,	$A
	demoinput R,	1
	demoinput UR,	2
	demoinput URC,	$13
	demoinput UR,	1
	demoinput R,	6
	demoinput ,	$25
	demoinput R,	1
	demoinput UR,	1
	demoinput URC,	$A
	demoinput RC,	7
	demoinput R,	$B
	demoinput ,	$2B
	demoinput R,	$1C
	demoinput ,	$18
	demoinput L,	6
	demoinput ,	$D
	demoinput R,	$21
	demoinput ,	5
	demoinput C,	4
	demoinput ,	$F
	demoinput UR,	5
	demoinput U,	1
	demoinput ,	$1F
	demoinput R,	6
	demoinput ,	2
	demoinput C,	7
	demoinput URC,	2
	demoinput UL,	8
	demoinput ,	$14
	demoinput R,	6
	demoinput ,	$16
	demoinput C,	2
	demoinput RC,	3
	demoinput URC,	5
	demoinput UR,	2
	demoinput R,	1
	demoinput ,	8
	demoinput R,	$C
	demoinput ,	$1A
	demoinput R,	$C
	demoinput RC,	7
	demoinput R,	6
	demoinput ,	$13
	demoinput R,	$12
	demoinput ,	$D
	demoinput C,	3
	demoinput RC,	5
	demoinput R,	5
	demoinput ,	$16
	demoinput R,	$D
	demoinput ,	$15
	demoinput C,	5
	demoinput RC,	1
	demoinput R,	3
	demoinput ,	$19
	demoinput R,	4
	demoinput ,	$2D
	demoinput C,	3
	demoinput RC,	8
	demoinput R,	5
	demoinput ,	$25
	demoinput LD,	$49
	demoinput L,	$48
	demoinput ,	$B
	demoinput L,	8
	demoinput ,	$15
	demoinput L,	$45
	demoinput UL,	1
	demoinput L,	1
	demoinput ,	$16
	demoinput R,	$16
	demoinput RD,	2
	demoinput ,	9
	demoinput L,	3
	demoinput UL,	$15
	demoinput ,	2
	demoinput UL,	2
	demoinput ULC,	$E
	demoinput UL,	$1C
	demoinput ,	8
	demoinput R,	$24
	demoinput UR,	1
	demoinput ,	8
	demoinput UL,	$23
	demoinput ULC,	$C
	demoinput UL,	$53
	demoinput ,	7
	demoinput R,	$27
	demoinput UR,	2
	demoinput U,	1
	demoinput ,	1
	demoinput U,	1
	demoinput UL,	$18
	demoinput ULC,	9
	demoinput UL,	$1B
	demoinput ,	$D
	demoinput R,	7
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1