	demoinput ,	$27
	demoinput L,	6
	demoinput ,	$2B
	demoinput R,	$1C
	demoinput ,	7
	demoinput L,	$A
	demoinput ,	7
	demoinput C,	2
	demoinput RC,	2
	demoinput URC,	3
	demoinput UR,	1
	demoinput R,	9
	demoinput ,	7
	demoinput R,	8
	demoinput ,	$4A
	demoinput R,	$C
	demoinput ,	3
	demoinput C,	4
	demoinput ,	$E
	demoinput R,	$1E
	demoinput ,	$14
	demoinput R,	7
	demoinput ,	$22
	demoinput R,	$22
	demoinput ,	7
	demoinput R,	$37
	demoinput ,	$1F
	demoinput R,	$1B
	demoinput ,	7
	demoinput C,	1
	demoinput RC,	5
	demoinput R,	$1A
	demoinput ,	5
	demoinput L,	$12
	demoinput ,	$20
	demoinput L,	$E
	demoinput ,	$D
	demoinput L,	$1F
	demoinput UL,	2
	demoinput L,	1
	demoinput ,	$A
	demoinput R,	$D
	demoinput ,	7
	demoinput L,	6
	demoinput UL,	2
	demoinput L,	$88
	demoinput LC,	8
	demoinput L,	5
	demoinput ,	5
	demoinput R,	$E
	demoinput UR,	$15
	demoinput R,	5
	demoinput ,	4
	demoinput L,	$18
	demoinput LC,	$14
	demoinput L,	$B
	demoinput ,	5
	demoinput UR,	$A
	demoinput R,	3
	demoinput ,	7
	demoinput L,	$19
	demoinput LC,	$C
	demoinput C,	5
	demoinput ,	3
	demoinput L,	$2F
	demoinput UL,	2
	demoinput L,	1
	demoinput ,	$14
	demoinput C,	$15
	demoinput ,	5
	demoinput R,	$1A
	demoinput ,	$11
	demoinput C,	$1E
	demoinput LC,	8
	demoinput L,	$F
	demoinput ,	$C
	demoinput C,	$1C
	demoinput LC,	6
	demoinput L,	$18
	demoinput LC,	1
	demoinput C,	$19
	demoinput LC,	6
	demoinput L,	$C
	demoinput ,	9
	demoinput C,	$20
	demoinput LC,	2
	demoinput L,	9
	demoinput ,	$C
	demoinput C,	$13
	demoinput RC,	8
	demoinput URC,	$D
	demoinput C,	1
	demoinput L,	$19
	demoinput ,	$1B
	demoinput R,	1
	demoinput UR,	8
	demoinput R,	$A
	demoinput UR,	$32
	demoinput R,	1
	demoinput ,	8
	demoinput C,	9
	demoinput LC,	$16
	demoinput L,	9
	demoinput ,	$28
	demoinput C,	$A
	demoinput LC,	$13
	demoinput L,	$F
	demoinput LC,	$F
	demoinput L,	$B
	demoinput ,	$A
	demoinput R,	$17
	demoinput RC,	1
	demoinput C,	$10
	demoinput RC,	5
	demoinput URC,	$1C
	demoinput UR,	6
	demoinput URC,	$D
	demoinput UR,	1
	demoinput R,	8
	demoinput ,	$A1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1