	demoinput ,	$12
	demoinput R,	$38
	demoinput RC,	5
	demoinput R,	$B
	demoinput ,	$13
	demoinput R,	$C
	demoinput ,	$20
	demoinput R,	$1C
	demoinput ,	$A
	demoinput R,	$21
	demoinput ,	$15
	demoinput L,	$17
	demoinput LC,	1
	demoinput C,	$10
	demoinput ,	$14
	demoinput L,	$18
	demoinput LD,	5
	demoinput D,	1
	demoinput ,	$25
	demoinput R,	$E
	demoinput ,	$47
	demoinput R,	$78
	demoinput ,	$61
	demoinput R,	$18
	demoinput ,	$17
	demoinput L,	4
	demoinput ,	$23
	demoinput R,	$1A
	demoinput RC,	3
	demoinput C,	2
	demoinput ,	$27
	demoinput C,	$A
	demoinput ,	$3B
	demoinput C,	$24
	demoinput ,	4
	demoinput R,	2
	demoinput ,	$2A
	demoinput L,	$14
	demoinput ,	$1A
	demoinput L,	$1C
	demoinput ,	$92
	demoinput R,	$22
	demoinput ,	$1A
	demoinput L,	5
	demoinput ,	$68
	demoinput L,	$24
	demoinput ,	$B
	demoinput R,	6
	demoinput ,	$88
	demoinput R,	$22
	demoinput ,	$2D
	demoinput R,	$28
	demoinput ,	$10
	demoinput R,	$36
	demoinput RC,	9
	demoinput R,	$46
	demoinput RC,	$A
	demoinput R,	$32
	demoinput ,	$9A
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
