	demoinput ,	$4B
	demoinput R,	$62
	demoinput RC,	$C
	demoinput R,	$48
	demoinput RC,	8
	demoinput R,	$3C
	demoinput RC,	9
	demoinput R,	$D2
	demoinput RC,	$11
	demoinput R,	$B
	demoinput ,	$F
	demoinput C,	$13
	demoinput RC,	5
	demoinput R,	$20
	demoinput ,	$C
	demoinput LD,	6
	demoinput L,	6
	demoinput ,	5
	demoinput C,	$C
	demoinput RC,	$F
	demoinput R,	$21
	demoinput ,	6
	demoinput C,	3
	demoinput RC,	$13
	demoinput R,	$10
	demoinput ,	$10
	demoinput R,	$C
	demoinput ,	1
	demoinput C,	$F
	demoinput RC,	5
	demoinput R,	$C
	demoinput ,	$1B
	demoinput R,	$D
	demoinput ,	7
	demoinput C,	$13
	demoinput RC,	8
	demoinput R,	$78
	demoinput RC,	1
	demoinput C,	$D
	demoinput LC,	5
	demoinput C,	8
	demoinput RC,	7
	demoinput R,	5
	demoinput ,	$10
	demoinput R,	$3A
	demoinput ,	$12
	demoinput R,	$E
	demoinput RC,	$B
	demoinput R,	$51
	demoinput RC,	$10
	demoinput R,	6
	demoinput ,	$15
	demoinput R,	$100
	demoinput R,	$57
	demoinput ,	$100
	demoinput ,	$40
	demoinput R,	1
	demoinput RC,	$F
	demoinput R,	$18
	demoinput ,	$18
	demoinput R,	6
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1