	demoinput ,	$8C
	demoinput R,	$38
	demoinput ,	$43
	demoinput R,	$5D
	demoinput ,	$6B
	demoinput R,	$60
	demoinput ,	$30
	demoinput R,	$2D
	demoinput ,	$22
	demoinput R,	4
	demoinput RC,	$31
	demoinput R,	9
	demoinput ,	$2F
	demoinput R,	$16
	demoinput ,	$10
	demoinput R,	$47
	demoinput ,	$1B
	demoinput R,	$100
	demoinput R,	$CB
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1
	demoinput ,	1